# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/squid
  block:

    - name: Ensure HTTP proxy server is not installed (CIS)
      become: true
      ansible.builtin.package:
        name:
          - 'squid'
        state: absent

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_squid'
